<?php
/**
 * Add is373_drupal_module as a menu item.
 */
function is373_drupal_module_menu() {
    $items['students/add'] = array(
        'title' => 'NJIT Student Form',
        'description' => 'Add NJIT Students.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('is373_drupal_module_form'),
        'access callback' => TRUE
    );

    $items['students/list'] = array(
        'title' => 'NJIT Student List',
        'description' => 'List NJIT students.',
        'page callback' => 'is373_drupal_module_list',
        'access callback' => TRUE
    );

    return $items;
}


/**
 * Select users from 'is373_drupal_module_students' table.
 */
function dbtng_students_load() {
    return db_select('is373_drupal_module_students', 's')
        ->fields('s', array('full_name', 'ucid'))
        ->execute();
}


/**
 * Page to list NJIT students as as table.
 */
function is373_drupal_module_list() {
    $output = '';

    if ($entries = dbtng_students_load()) {
        $rows = array();

        foreach ($entries as $entry)
            $rows[] = array_map('check_plain', (array) $entry);

        $header = array(
            t('Name'),
            t('UCID'),
        );

        $output .= theme('table', array(
            'header' => $header,
            'rows' => $rows,
        ));
    }
    else
        drupal_set_message(t('No entries have been added yet.'));

    return $output;
}


/**
 * Form to add NJIT students.
 */
function is373_drupal_module_form($form, &$form_state) {
    $form['full_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Full Name'),
        '#maxlength' => 255,
        '#required' => TRUE,
    );
    $form['ucid'] = array(
        '#type' => 'textfield',
        '#title' => t('UCID'),
        '#maxlength' => 32,
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Add Student'),
    );

    return $form;
}


/**
 * Validate NJIT student form submission.
 * - Ensure no duplicate UCIDs.
 */
function is373_drupal_module_form_validate($form, &$form_state) {
    $countStr = db_select('is373_drupal_module_students')
        ->fields(NULL, array('ucid'))
        ->condition('ucid', $form['ucid']['#value'])
        ->countQuery()
        ->execute()
        ->fetchField();

    if (intval($countStr) > 0)
        form_set_error('ucid', t('UCID already exists!'));
}


/**
 * Add NJIT student to 'is373_drupal_module_students' database table.
 */
function is373_drupal_module_form_submit($form, &$form_state) {
    drupal_set_message(t('NJIT Student added!'));
    db_insert('is373_drupal_module_students')
        ->fields(array(
            'full_name' => $form['full_name']['#value'],
            'ucid' => $form['ucid']['#value'],
        ))
        ->execute();
}
