<?php
/**
 * Add is373_drupal_module as a menu item.
 */
function is373_drupal_module_menu() {
    $items['students/add'] = array(
        'title' => 'NJIT Student Form',
        'description' => 'Add NJIT Students.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('is373_drupal_module_form'),
        'access callback' => TRUE
    );

    return $items;
}


/**
 * Form to add NJIT students.
 */
function is373_drupal_module_form($form, &$form_state) {
    $form['full_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Full Name'),
        '#maxlength' => 255,
        '#required' => TRUE,
    );
    $form['ucid'] = array(
        '#type' => 'textfield',
        '#title' => t('UCID'),
        '#maxlength' => 32,
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Add Student'),
    );

    return $form;
}
